version: "3.9"

services: 
  income_db:
    image: postgres
    environment: 
      - POSTGRES_DB=income_service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=7426
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - incomenetwork
  
  web: 
    build: .
    restart: always
    ports: 
      - "6000:6000"
    depends_on: 
      - income_db
    links:
      - income_db:income_db
    networks:
      - incomenetwork
    command: bash -c "python manage.py migrate && gunicorn --bind 0.0.0.0:6000 --workers=4 budget_tracker_income_service.wsgi"
networks:
  incomenetwork:
    driver: bridge